/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* User should hand edit this file.
********************************************************************************/

/**
 * @param {Object} event
 * @base onload
 * @returns {Boolean}
*/
app.onload = function() {
	// TODO:: Do your app initialization job
	console.log("loaded");
};

/**
 * @param {Object} event
 * @base onunload
 * @returns {Boolean}
*/
app.onunload = function() {
	// TODO:: Do your app termination job
	console.log("unloaded");
};

/**
 * @param {Object} event
 * @base onshow
 * @returns {Boolean}
*/
app.onshow = function() {
	// TODO:: Do your job on visible
	console.log("onshown");
};

/**
 * @param {Object} event
 * @base onhide
 * @returns {Boolean}
*/
app.onhide = function() {
	// TODO:: Do your job on invisible
	console.log("onhidden");
};

/**
 * @param {Object} event
 * @base onpagebeforechange
 * @returns {Boolean}
 */
app.onpagebeforechange = function() {
	// TODO:: Do your job before switching from the current page
	console.log("onpagebeforechange");
};

/**
 * @param {Object} event
 * @base onpagebeforeload
 * @returns {Boolean}
 */
app.onpagebeforeload = function() {
	// TODO:: Do your job before an external page is loaded
	console.log("onpagebeforeload");
};

/**
 * @param {Object} event
 * @base onpagechange
 * @returns {Boolean}
 */
app.onpagechange = function() {
	// TODO:: Do your job after switching from the current page to the new page
	console.log("onpagechange");
};

/**
 * @param {Object} event
 * @base onpagechangefailed
 * @returns {Boolean}
 */
app.onpagechangefailed = function() {
	// TODO:: Do your job when the page switching fails
	console.log("onpagechangefailed");
};

/**
 * @param {Object} event
 * @base onpageload
 * @returns {Boolean}
 */
app.onpageload = function() {
	// TODO:: Do your job after an external page is loaded
	console.log("onpageload");
};
/**
 * @param {Object} event
 * @base _page1_page
 * @returns {Boolean}
*/
_page1_page.prototype.button1_ontouchstart = function(event) {
	
};

